package com.investmonitor.api.invest_monitor_api.models.enums;

public enum MarketType {CRIPTO,
    CREDITO,MULTI,LOGISTICA,LAJES,DESENVOLVIMENTO,FUNDOS,SHOPPING, PAPEL,MISTO,AGRICOLA,INDUSTRIAL, TIJOLO, RESIDENCIAL, AGRO,HOSPITALAR,BANCOS,BEBIDAS,MINERACAO,PETROLEO_GAS,INDUSTRIA,ALIMENTOS,ENERGIA, SIDERURGIA,PAPEL_CELULOSE,VAREJO,LOCACAO,CONSTRUCAO,FARMACIAS, SAUDE,FINTECH,EDUCACAO,TELECOM,AERONAUTICA,CIA_AEREA,COSMETICOS,TURISMO,SEGUROS}
   
